### PR TITLE
New Approach via Batch Scripts

### PR DESCRIPTION
**Pull request by zner0L**

### CODE REVIEW

**Comment by emilengler** [comment]
Hi, can you explain why you want to merge this ? Batch can't detect when a Process is done.
~ Greetings Emil

**Comment by zner0L** [comment]
Batch runs all lines in one thread. So each line has to wait for the
termination of the others.

Emil Engler wrote:

**Comment by emilengler** [comment]
In C# too, the program is starting silent and after its done, the next process is starting. We already used this program with the new tablet classes.

~Greetings Emil

**Comment by zner0L** [comment]
Well, I don't doubt that the current branch works. Still, a .NET
application seems overkill to me for just calling other executables.
That's what batch files were made for.

Emil Engler wrote:

**Comment by emilengler** [comment]
We already developed a batch installer a long time ago. But we decided to recode it in c# like a further update function etc I will upload the old batch version as soon as I can. I will close this request now. If you a have any questions, feel free to write me an email which is linked on my github profile.

~ Greetings Emil

**Pull request closed without merging**
